# lightning.pytorch==2.4.0
seed_everything: false
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  logger:
    - class_path: TensorBoardLogger
      init_args:
        save_dir: "."
        default_hp_metric: false
  callbacks:
    - class_path: LearningRateMonitor
    - class_path: ModelCheckpoint
      init_args:
        save_last: link
        dirpath: models
        filename: rrm-{hp_metric:0.2f}
        mode: max
        auto_insert_metric_name: false
        monitor: hp_metric
    - class_path: ModelCheckpoint
      init_args:
        save_last: false
        dirpath: models
        filename: rrm
  fast_dev_run: false
  max_epochs: 3
  min_epochs: 0
  max_steps: -1
  min_steps: -1
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: .2
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 10
  log_every_n_steps: 500
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 2
  gradient_clip_val: 2
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: true
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  class_path: radiometric_reconstruction_module
  init_args:
    lr: 2e-3
    strict: true
    size: 300
    w_decay: 1e-4
data:
  class_path: msi2slstr_datamodule
  init_args:
    batch_size: 8
    t_size: [300, 3]
optimizer: null
lr_scheduler: null
ckpt_path: null
